---

name: "Compile"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  compile:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8.10"
          architecture: [ "x64" , "x86" ]
      - name: Compile
        run: |
          git clone https://github.com/juruo888/Actions-Test.git
          python --version
          cd Actions-Test
          python compile.py
