---

name: "Compile"

on:
  push:
    branches: [ "master" ]

jobs:
  windows:
    name: "Compile on Windows"
    if: startsWith( github.event.head_commit.message, 'VER' )
    runs-on: windows-latest
    steps:
      - name: Install Python 3.8.10 x64
        uses: actions/setup-python@v4
        with:
          python-version: "3.8.10"
          architecture: "x64"
      - name: Install Python 3.8.10 x86
        uses: actions/setup-python@v4
        with:
          python-version: "3.8.10"
          architecture: "x86"
      - name: Clone repository
        run: |
          git clone https://github.com/juruo888/Actions-Test.git
      - name: Compile
        run: |
          cd Actions-Test
          python compile.py
      - name: Get version and log
        env:
          MSG: ${{ toJSON(github.event.commits.*.message) }}
          VER: ""
          VERSION: ""
          FILEPATH: ""
        run: |
          cd Actions-Test
          python ./.github/compile/version.py
          "VER=1.2.0" >> $env:GITHUB_ENV
          "VERSION=1.1.0.9.1.1" >> $env:GITHUB_ENV
          "FILEPATH=Releases\ScratchOff_1.1.0.9.1.1.zip" >> $env:GITHUB_ENV
      - name: Publish to Releases
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.VERSION }}
          tag_name: ${{ env.VER }}
          body_path: ./log.txt
          prerelease: ${{ contains( env.VERSION, '-' ) }}
          files: ${{ env.FILEPATH }}
