---

name: "Compile"

on:
  push:
    branches: [ "master" ]

jobs:
  windows:
    name: "Compile on Windows"
    if: startsWith( github.event.head_commit.message, 'VER' )
    runs-on: windows-latest
    steps:
      - name: Install Python 3.8.10 x64
        uses: actions/setup-python@v4
        with:
          python-version: "3.8.10"
          architecture: "x64"
      - name: Install Python 3.8.10 x86
        uses: actions/setup-python@v4
        with:
          python-version: "3.8.10"
          architecture: "x86"
      - name: Clone repository
        run: |
          git clone https://github.com/juruo888/Actions-Test.git
          git clone https://github.com/juruo888/ScratchOff-Pictures.git
          mv ScratchOff-Pictures pictures
          cd pictures
          Remove-Item -Path .git
      - name: Compile
        run: |
          cd Actions-Test
          python compile.py
      - name: Get version
        run: python ./.github/compile/version.py
      # - name: Publish to Releases
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     tag_name: "ScratchOff v"+${{ env.VER }}
      #     body_path: github.event.head_commit.message
      #     prerelease: ${{ contains( env.VER, '-' ) }}
      #     files: Releases/ScratchOff
