---

name: "Compile"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  compile:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: |
          git clone https://github.com/juruo888/Actions-Test.git
          python --version
          cd Actions-Test
          python compile.py
